=== Maxbester/dbsynchro/DbSyncTool/validation.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="portType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="65535" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="emailAddressType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+@[^\.]+\..+" />
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="ipAddressType">
		<xs:restriction base="xs:string">
			<xs:pattern
				value="((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\.){3}((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9])))(\-((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\.){3}((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))))?|localhost" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="smtpType">
		<xs:sequence>
			<xs:element name="address" type="ipAddressType" minOccurs="1"
				maxOccurs="1" default="localhost" />
			<xs:element name="port" type="portType" minOccurs="1"
				maxOccurs="1" default="25" />
			<xs:element name="login" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="password" type="xs:string" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="email">
		<xs:sequence>
			<xs:element name="smtpConfig" type="smtpType" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="from" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="subject" type="xs:string" default="Synchronisation failed"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="recipient" type="emailAddressType"
				minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="database">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="url" type="xs:string" default="localhost"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="login" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="password" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="driver" type="xs:string" default="com.mysql.jdbc.Driver"
				minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="email" type="email" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="database" type="database" minOccurs="2"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Maxbester/dbsynchro/DbSyncTool/validation.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validation.xsd">
  <email>
    <smtpConfig>
      <address>localhost</address>
      <port>25</port>
      <login>login</login>
      <password>password</password>
    </smtpConfig>
    <from>from</from>
    <subject>Synchronisation failed</subject>
    <recipient>recipient</recipient>
  </email>
  <database>
    <name>name</name>
    <url>localhost</url>
    <login>login</login>
    <password>password</password>
    <driver>com.mysql.jdbc.Driver</driver>
  </database>
  <database>
    <name>name</name>
    <url>localhost</url>
    <login>login</login>
    <password>password</password>
    <driver>com.mysql.jdbc.Driver</driver>
  </database>
</config>
